### ISSUE TITLE
Ability to continue measuring post-click performance in a contextual + FLOC set up

### ISSUE THREAD

**Issue by cgouvernet** [jkarlin/floc#28]
Today, post-click performance measurement and optimization is done thanks to third-party cookies, or URL decoration (either UTM sources or a click id in the decoration).

Third-party cookies are going away, but will we still be able to use link decoration for performance measurement and optimization?

I understand from FLoC proposal that cohorts will be large enough to guarantee privacy and keep authorizing click decorations and UTM sources.

Can you confirm it?

**Comment by michaelkleber** [comment]
For post-click performance measurement, no matter what the targeting technique, see the [Conversion Measurement API](https://github.com/WICG/conversion-measurement-api) proposals.
