### ISSUE TITLE
Performance measurement: ABtest-ability and incrementality

### ISSUE THREAD

**Issue by cgouvernet** [jkarlin/floc#29]
In digital marketing, AB-testing is usually performed by splitting an audience into populations based on a hash of the user id. By building these independent splits, the advertiser can:

 - measure the impact of a feature on users and thus improve his marketing strategy

 - measure the incrementality (the overall business uplift) brought by a marketing campaign

**Is AB testing supported by the FLoC proposal?**

As in FLoC, the uid is meant to be replaced by a cohort id, one could think of taking the hash of a cohort id to build the population splits. This is not a viable option because:

 - the dependence of cohort ids. By design, the cohort ids are chosen to represent users interests. A sports retailer may simply not statistically have the same performance on tennis-interested users (assuming there will be a cohort for such users) against those interested in football.

 - the loss of granularity: depending on his campaign setup, the advertiser may even be targeting a unique cohort id, that may fall into population A or B (given the result of hash(cohort_id)) but not into both.

**Comment by michaelkleber** [comment]
Bonjour Cédric,

You're correct, FLoC is not particularly well suited to splitting up a population for A/B experimentation, for exactly the reasons you describe.

The Web Advertising Business Group's ["Advertising Use Cases" doc](https://github.com/w3c/web-advertising/blob/master/support_for_advertising_use_cases.md) includes a bunch of discussions of Lift Measurement, and the recent Chrome proposal for [Fenced Frames has a section](https://github.com/shivanigithub/fenced-frame/#conversion-lift-measurement) about this use case.  The privacy properties of these proposals generally revolve around the browser performing A/B diversion, and a server learning the results in aggregate, but not knowing whether an individual event showed the A or B creative.
