### ISSUE TITLE
Addressed Category

### ISSUE THREAD

**Issue by fprivitera** [jkarlin/floc#9]
this document starts saying that you will cover only the (2) category, I think that this can be more clear. I have the following considerations.

1) if you would like to treat the solution as an alternative for user-ID, the document should also cover the third category, because actions are related to the user too.

2) if you would like that the FLoC can represent a great solution for tailored advertising based on user history it is perfect. It's covering greatly the targeting capabilities based on client-side information, like web history, nut it is not covering the first party user segment information, that usually a DSP as server-side, for instance, an advertiser can have in their CRM the propensity to churn.

**Comment by michaelkleber** [comment]
Thanks, good point!  I will clarify.
